---
title: "temp"
author: "Jeff"
date: "23/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(spotifyr)
library(jsonlite)
library(RSQLite)
```

```{r}
## Authentication
Sys.setenv(SPOTIFY_CLIENT_ID = "badf25184ba2489186c38825620b7adb")
Sys.setenv(SPOTIFY_CLIENT_SECRET = "07f292be15e84c209880cb424f92e4a0")

access_token <- get_spotify_access_token()
```


```{r}
url <- "https://www.googleapis.com/books/v1/volumes?q=data&startIndex=1&maxResults=40"

response <- fromJSON(url, flatten = TRUE)

data <- response$items

```

```{r}
json_url <- "https://www.stat.auckland.ac.nz/~fergusson/stats220/data/lab3b_json5.json"

song_data <- fromJSON(json_url)

#Q1
song_data <- fromJSON(json_url)

#Q2
song_data %>% pull(duration_ms) %>% length()

#Q3
song_data %>% pull(duration_ms) %>% median()

#Q4
song_data %>% pull(track_popularity) %>% unique() %>% length()

#Q5
song_data <- fromJSON(json_url) %>%
  separate_rows(artist_name, sep = ", ") %>% pull(artist_name) %>%
  unique() %>%
  length()

song_data

#Q6
song_data_filtered <- song_data %>%
  filter(track_popularity > 68 & str_detect(str_to_lower(artist_genre), "pop"))

nrow(song_data_filtered)

#Q7
personal_songs <- song_data %>%
  mutate(pop_songs = ifelse(str_detect(str_to_lower(artist_genre),
                                           "pop"),"yes","no"))

personal_songs

#Q8
personal_songs <- song_data %>%
  mutate(pop_songs = ifelse(str_detect(str_to_lower(artist_genre),
                                           "pop"),"yes","no"))

personal_songs %>%
  group_by(pop_songs) %>%
  summarise(median_duration = median(track_popularity))


#Q9-Q10
long_songs <- song_data %>%
  mutate(track_name_num_words = str_count(track_name, " ") +1) %>%
  mutate(track_name_num_words_mores = ifelse(track_name_num_words > 3, "yes", "no"))

long_songs

sum(long_songs$track_name_num_words_mores == "yes")
```